### ISSUE TITLE
how to detect the Alu, L1 and SVA

### ISSUE THREAD

**Issue by cangfengzhe** [tjiangHIT/rMETL#4]
rMETL is a good tools to detect ME. 
In the file of super_TE.fa, there are sequence of Alu, L1 and SVA.  
 But in the result, only find the Chromsome,    Breakpoint,  SV length. I want to know how to  detect the Alu, L1 and SVA.

**Comment by tjiangHIT** [comment]
Hello, thanks for using rMETL.
In stage of 'calling', whatever the output file type selected, you will acquire detailed info about ME type.
For BED format, you will get Chromsome, Breakpoint, SV length and SV type (e.g. **<INS:ME:L1>**).
For VCF format, SV type will also be obtained in column 'ALT' (e.g. **<INS:ME:L1>**).
Please ensure runing rMETL with correct commands.
I'll close this issue for now. Feel free to reopen if you have further questions :)
