### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'output'

### ISSUE THREAD

**Issue by Soniazumalave** [tjiangHIT/rMETL#6]
Hi there, 

I am getting this error when running rMETL detection (v1.0.2). It does generate the signatures and brokes like this:

```
Traceback (most recent call last):
  File "/apps/0_external_tools/rMETL/rMETL.py", line 57, in <module>
    parseArgs()
  File "/apps/0_external_tools/rMETL/rMETL.py", line 54, in parseArgs
    STAGES[args.stage](args.options)
  File "/apps/0_external_tools/rMETL/src/rMETL_extraction.py", line 566, in run
    load_sam_multi_processes(args)
  File "/apps/0_external_tools/rMETL/src/rMETL_extraction.py", line 500, in load_sam_multi_processes
    output_p = args.output if args.output.endswith('/') else "%s/"%(args.output)
AttributeError: 'Namespace' object has no attribute 'output'

```

My command has been:
python2.7 rMETL detection -t 8 -x ont \
/pathToBam/sample.bam \
/pathToReference/hs37d5.fa \
/pathTooutputDir \
/pathTooutputDir/sampleName

/pathTooutputDir existed already, but /pathTooutputDir/sampleName didn't, but don't think is related to that since you have a mkdir command. 

Shouldn't it be args.output_dir instead?

Thank you in advance! 

Sonia

**Comment by tjiangHIT** [comment]
Hi @Soniazumalave 
Thanks for your bug reporting. I am sorry for my carelessness. As you mentioned, I miswrote _output_dir_ into _output_ and an **AttributeError** was raised. Now I have fixed this bug and please use the latest version of  rMETL in your work.
If you have any questions about rMETL, please contact with me.
Thanks for using rMETL.
Cheers!

**Comment by Soniazumalave** [comment]
Hi @tjiangHIT, 

Thanks for your answer. It does work now! I am closing this issue. 


Regards, 
Sonia
