### ISSUE TITLE
Allele Frequency not output in VCF

### ISSUE THREAD

**Issue by gbdias** [tjiangHIT/rMETL#7]
Hi @tjiangHIT 

I tried running rMETL and all steps seem to have worked fine. However, in my final VCF I don't see the AF (Allele Frequency) values in the Info field.

```
chr2L   1686721 16      T       <INS:ME:Juan#LINE/Jockey>       .       PASS    PRECISE;SVTYPE=INS;SVLEN=237;END=1686957;SAMPLE=None;STRAND=-   GT:DV:DR        1/1:64:0
chr2L   1829995 17      G       <INS:ME:TART-A#LINE/Jockey>     .       PASS    PRECISE;SVTYPE=INS;SVLEN=74;END=1830068;SAMPLE=None;STRAND=+    GT:DV:DR        0/1:46:12
chr2L   2051753 18      G       <INS:ME:hopper#DNA/Transib>     .       PASS    PRECISE;SVTYPE=INS;SVLEN=950;END=2052702;SAMPLE=None;STRAND=+   GT:DV:DR        0/1:24:29
chr2L   2051803 19      G       <INS:ME:hopper#DNA/Transib>     .       PASS    PRECISE;SVTYPE=INS;SVLEN=1512;END=2053314;SAMPLE=None;STRAND=+  GT:DV:DR        1/1:84:0
```

Does rMETL outputs this information by default or am I missing something in my calling command?
```
rMETL calling $SAM $REF vcf .
```

Thank you

**Comment by tjiangHIT** [comment]
Hello @gbdias,

Thanks for using rMETL and pointing this.
I am sorry that rMETL cannot support to output AF for each mobile element call, because the current version of rMETL is just for detect ME from a single person not for the cohort. 
Thanks.

Tao

**Comment by gbdias** [comment]
thank you @tjiangHIT
