### ISSUE TITLE
install rMETL in 2023

### ISSUE THREAD

**Issue by 120L021101** [tjiangHIT/rMETL#8]

**Comment by 120L021101** [comment]
Note that pip(>=21.0) doesn't support python2 anymore, pysam has removed python2.X since version 0.21(the latest). I found similar problems when installing biopython, and I changed to another version that had closed released time to rMETL, and that was 1.76.

**Comment by 120L021101** [comment]
Note that pip(>=21.0) doesn't support python2 anymore, pysam has removed python2.X since version 0.21(the latest) as well. Besides, I found similar problems when installing biopython, and I changed to another version(1.76) that had closed released time compared to rMETL.

**Comment by 120L021101** [comment]
Besides, rMETL used "get_index_statistics()" of pysam, which was added since 0.15.0, so even if 0.8.0 supports python2, you may found runtime errors as well.

**Comment by 120L021101** [comment]
my instructions(I already have samtools):
conda create -n rMETLenv python=2.7
conda activate rMETLenv
pip install pip==19.0
pip install cython
pip install pysam==0.19.0
pip install Biopython==1.76
conda install -c bioconda ngmlr
pip install cigar
#change current dir to rMETL/
python setup.py install

**Comment by tjiangHIT** [comment]
Thanks @120L021101,

Now I have mentioned this in the README to inform other users.
Many thanks for your work.

Tao
